# Generated by Django 4.2.3 on 2023-07-27 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auctionlisting_watchlist_alter_auctionlisting_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='watchlist',
        ),
    ]
