# Generated by Django 4.2.3 on 2023-07-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_remove_bid_bidder_alter_auctionlisting_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bid',
        ),
    ]
