# Generated by Django 4.2.3 on 2023-08-07 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_alter_comment_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='listed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.auctionlisting'),
        ),
    ]
